# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 67b8a7d1ba8df8c37f1b31497d38d65c39c7ab492e891ab97d4e981db1aa82ed01c9afb48138e5443c902f9d657e40f3f99f462571fd97d96aa443333c33a668

test:
  secret_key_base: 9b673afbe01c50ab6afcb8a2815f3f1437260a36f158909d4cc04479f4a82c896a960a185ce0200ece45100c42ae3bc88e6755c5418c8f7830ce6c57e9e981fc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
